### ISSUE TITLE
Shields are off-center when rendered as items

### ISSUE THREAD

**Issue by MattSturgeon** [XVTEAM/Faithful#6]
This is actually a [vanilla issue](https://bugs.mojang.com/browse/MC-95103) but it might make sense to include the [fix](https://bugs.mojang.com/secure/attachment/107789/shield.zip) posted on the vanilla bug in Faithful unless mojang fix the issue before 1.12.

![shield](https://cloud.githubusercontent.com/assets/5046562/26166422/5ec69992-3b2b-11e7-8380-baee47739c7c.png)

**Comment by xMrVizzy** [comment]
Yeah, it's would be cool to fix this, in next update i fix it!

**Comment by xMrVizzy** [comment]
Thank you!
