### ISSUE TITLE
New powered rail texture

### ISSUE THREAD

**Issue by CrazyBatkin** [XVTEAM/Faithful#7]
There's a small detail about the new powered rail texture that is reaaaally unsatifying I think... x) This small red thing on the side of the rail should be one pixel larger than it is. (Look on the pictures)
![2017-05-27_19 30 49](https://cloud.githubusercontent.com/assets/29003872/26523218/08e44476-4313-11e7-9cb4-1cd216cc2a73.png)
![2017-05-27_19 30 32](https://cloud.githubusercontent.com/assets/29003872/26523219/08e7a152-4313-11e7-9e0d-655a45dfc328.png)

**Comment by xMrVizzy** [comment]
Yeah, I know.

**Comment by CrazyBatkin** [comment]
Is it intentionnal ? If yes I'll just close that issue ;)

**Comment by EltrutLikes** [comment]
I think this is still a problem. I understand Faithful is supposed to use one-pixel wide lines, but I think this would look better if the golden part of the rail was two pixels wide. The red can stay as it is, just the golden part.
